# -*- coding: utf-8 -*-
"""HangMan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N_fFEWdVllJfykHBcr9sdnM-4U3eJhx2
"""

import random

# List of word categories and corresponding words
word_categories = {
    "fruits": ["apple", "banana", "cherry", "durian", "elderberry"],
    "animals": ["cat", "dog", "elephant", "giraffe", "hippopotamus"],
    "colors": ["red", "blue", "green", "yellow", "orange"]
}

# Maximum number of incorrect guesses allowed
max_guesses = 6

def select_word(category):
    """Selects a random word from the specified category."""
    if category not in word_categories:
        print("Invalid category. Selecting a word from the 'fruits' category.")
        category = "fruits"

    word_list = word_categories[category]
    return random.choice(word_list)

def display_word(word, guesses):
    """Displays the word with correctly guessed letters and underscores for unknown letters."""
    display = ""
    for letter in word:
        if letter in guesses:
            display += letter
        else:
            display += "_"
    print(display)

def play_hangman():
    """Plays a game of Hangman."""
    print("Welcome to Hangman!")
    print("Guess the letters to uncover the hidden word.")
    print(f"You have {max_guesses} incorrect guesses allowed.")

    category = input("Select a word category (fruits, animals, colors): ")
    word = select_word(category.lower())
    word = word.lower()

    guesses = set()
    incorrect_guesses = 0

    while incorrect_guesses < max_guesses:
        print("\n")
        display_word(word, guesses)
        guess = input("Enter a letter: ").lower()

        if guess in guesses:
            print("You already guessed that letter. Try again.")
            continue

        guesses.add(guess)

        if guess in word:
            print("Correct guess!")
            if all(letter in guesses for letter in word):
                print("Congratulations! You uncovered the word:", word)
                break
        else:
            incorrect_guesses += 1
            print("Incorrect guess.")

    if incorrect_guesses == max_guesses:
        print("You ran out of guesses. Game over!")
        print("The word was:", word)

    play_again = input("Do you want to play again? (yes/no): ")
    if play_again.lower() == "yes":
        play_hangman()
    else:
        print("Thank you for playing Hangman!")
t
# Start the game
play_hangman()

